[project]
name = "output-guardrail"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.104.1",
    "openai-agents>=0.2.10",
]

